#Name of the application
spring:
  application:
    name: ZuulService

#register api gateway service  to eureka server  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
instance:
  hostname: localhost

#specify the port number of gateway
server:
  port: 8989

#now specify the zuul configurations 
zuul:
  prefix: /app
  routes:
    USER-DETAIL-SERVICE:
      path: /users/**
      service-id: USER-DETAIL-SERVICE
    FLIGHT-DETAIL-SERVICE:
      path: /flights/**
      service-id: FLIGHT-DETAIL-SERVICE
    BOOK-FLIGHT-SERVICE:
      path: /bookings/**
      service-id: BOOK-FLIGHT-SERVICE

ribbon:
  eager-load:
    enabled: true
      